### ISSUE TITLE
"PUT" Method Not Working

### ISSUE THREAD

**Issue by arthurliutw** [dino596/test_api#1]
I initially drafted an API with only the "GET" method. After making sure that the "GET" method worked, I decided to add the other HTTP methods, "POST", "PUT", and "DELETE". "POST" and "DELETE" works, but "PUT" does not work. I will be reviewing the code through ChatGPT to see how I can fix it.

Currently, it does not give an error message, but does not update when called.

**Comment by arthurliutw** [comment]
Added add_argument to parser in "PUT" method.
Added an if condition to test which attributes to edit in the db.
Fixed "PUT" method, API and backend should be fully functional now, tested with VSCode Postman extension.

**Comment by JasonGao76** [comment]
Hey Arthur, I tested out the POST, GET, and PUT, and they all worked. Here are the outputs and what I changed on my local machine:
POST:
![image](https://github.com/dino596/test_api/assets/142445641/442da9a6-3f70-436c-8a94-8fdd529c378b)

GET:
Specific class: 
![image](https://github.com/dino596/test_api/assets/142445641/f6ef1e62-9eda-4e61-9b9c-220aecd40e6a)
Whole datalist:
![image](https://github.com/dino596/test_api/assets/142445641/fd52bfc5-4ab5-41a4-9960-bdea5d04c4bc)

PUT:
![image](https://github.com/dino596/test_api/assets/142445641/ead6cd5f-268b-498e-a719-27d4ff34e27c)

Code works so that's good, but is it possible to add some comments in the code? I understand most of the code from working with you on it, but sometimes it's confusing to read through it and others may not understand as easily.
